<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="89959" started-at="2018-09-20T15:43:44Z" finished-at="2018-09-20T15:45:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="89959" started-at="2018-09-20T15:43:44Z" finished-at="2018-09-20T15:45:14Z">
      <class name="test.TestDeletePostWithAttachment">
        <test-method status="PASS" signature="setup()[pri:0, instance:test.TestDeletePostWithAttachment@26653222]" name="setup" is-config="true" duration-ms="17069" started-at="2018-09-20T15:43:44Z" finished-at="2018-09-20T15:44:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="test_Delete_Chatter_Post_Attachment()[pri:0, instance:test.TestDeletePostWithAttachment@26653222]" name="test_Delete_Chatter_Post_Attachment" duration-ms="71689" started-at="2018-09-20T15:44:01Z" finished-at="2018-09-20T15:45:13Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at test.TestDeletePostWithAttachment.test_Delete_Chatter_Post_Attachment(TestDeletePostWithAttachment.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Delete_Chatter_Post_Attachment -->
        <test-method status="PASS" signature="exit()[pri:0, instance:test.TestDeletePostWithAttachment@26653222]" name="exit" is-config="true" duration-ms="1157" started-at="2018-09-20T15:45:13Z" finished-at="2018-09-20T15:45:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
      </class> <!-- test.TestDeletePostWithAttachment -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
